name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    services:
      questdb:
        image: questdb/questdb
        ports:
          - 9000:9000

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: curl, mbstring, zip
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-suggest --no-progress

      - name: Execute tests
        run: |
          vendor/bin/phpunit --verbose
        env:
          QUEST_DB_URI: http://127.0.0.1:${{ job.services.mysql.ports[9000] }}
